<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Beacon.Contracts\Beacon.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Beacon.Api\Beacon.Api.csproj" />
    <ProjectReference Include="..\..\src\Beacon.Domain\Beacon.Domain.csproj" />
    <ProjectReference Include="..\..\src\Beacon.Infrastructure\Beacon.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Beacon.Application\Beacon.Application.csproj" />
  </ItemGroup>

</Project>
